upper_layer_send: true
upper_layer_receive: true
lower_layer_send: true
lower_layer_receive: true
remote_receive: true
remote_send: true

ecu_local_ip: "172.16.16.167"
ecu_local_port: 8181
ecu_remote_ip: "172.16.16.168"
ecu_remote_port: 8181

remote_local_ip: "192.168.1.18"
remote_local_port: 13010
remote_remote_ip: "192.168.1.24"
remote_remote_port: 13010

reconfig: false
send_default_when_no_msg: true
log_rawdata: true
publish_rawdata: true
force_autonomous: false

limit_speed: 17.0
limit_thousand_curv: 1300

files: []