upper_layer_send: true
upper_layer_receive: false
lower_layer_send: true
lower_layer_receive: false
remote_receive: true
remote_send: true

ecu_local_ip: "172.16.16.167"
ecu_local_port: 8181
ecu_remote_ip: "172.16.16.168"
ecu_remote_port: 8181

remote_local_ip: "172.16.16.167"
remote_local_port: 13020
remote_remote_ip: "172.16.16.168"
remote_remote_port: 13020

reconfig: true
send_default_when_no_msg: false
log_rawdata: true
publish_rawdata: true