upper_layer_send: true
upper_layer_receive: true
lower_layer_send: true
lower_layer_receive: true

reconfig: false
send_default_when_no_msg: false
verbose_log: false

ecu_ip: "192.168.1.222"
ecu_port: 8080
udp_server_port: 8081

publish_period: 20 #ms
essential_msg_max_period: 100 #ms
check_period: 250 #ms
well_work_display_period: 1000 #ms