upper_layer_send: true
upper_layer_receive: true
lower_layer_send: true
lower_layer_receive: true
remote_receive: true
remote_send: true

ecu_local_ip: "192.168.0.111"
ecu_local_port: 8400
ecu_remote_ip: "192.168.0.10"
ecu_remote_port: 8500

remote_local_ip: "192.168.0.111"
remote_local_port: 13010
remote_remote_ip: "192.168.0.101"
remote_remote_port: 13010

reconfig: false
send_default_when_no_msg: true
log_rawdata: false
publish_rawdata: false