upper_layer_send: true
upper_layer_receive: false
lower_layer_send: true
lower_layer_receive: true

ecu_ip: "172.16.16.168"
ecu_port: 8181
udp_server_port: 8181

reconfig: true
send_default_when_no_msg: false
log_rawdata: true
publish_rawdata: true